apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: oscar
  name: oscar
spec:
  ingressClassName: nginx
  rules:
    -  http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: oscar
              port:
                number: 8080